name: Build
on:
  workflow_call:

jobs:
  gradle:
    name: Gradle build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.5
      - name: Run build and tests
        run: ./gradlew buildAll