name: Docker image
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

permissions:
  id-token: write
jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
  jib:
    needs:
      - build
    if: github.repository_owner == 'HBTGmbH'
    name: Create and publish Docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: arn:aws:iam::313329311652:role/PushContainerImagesGithubActions
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
      - name: Create and publish docker image
        if: github.event_name == 'push' && github.ref_type == 'tag'
        run: ./gradlew -Prelease.useLastTag=true final jib
      - name: Create and publish docker image
        if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref_type == 'branch')
        run: ./gradlew snapshot jib
