name: Docker image
on:
  push:
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
  jib:
    needs:
      - build
    if: github.repository_owner == 'HBTGmbH'
    name: Create and publish Docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.5
          cache-read-only: true
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Create and publish docker image
        if: github.event_name == 'push'
        run: ./gradlew -Prelease.useLastTag=true final jib
        env:
          USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Create and publish docker image
        if: github.event_name == 'pull_request'
        run: ./gradlew snapshot jib
        env:
          USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
